App_Feed/urls.py
from django.urls import path
from App_Feed import views
from App_Feed.views import DeleteBlog

app_name = 'App_Feed'

urlpatterns = [
    path('', views.BlogList.as_view(), name='blog_list'),
    path('write/', views.CreateBlog.as_view(), name='create_blog'),
    path('details/<slug:slug>', views.blog_details, name='blog_details'),
    path('liked/<pk>/', views.liked, name='liked_post'),
    path('unliked/<pk>/', views.unliked, name='unliked_post'),
    path('my-blogs/', views.MyBlogs.as_view(), name='my_blogs'),
    path('edit/<pk>/', views.UpdateBlog.as_view(), name='edit_blog'),
    path('delete/<pk>/', DeleteBlog.as_view(), name='delete_blog'),
]

App_Login/urls.py
from django.urls import path
from App_Login import views

app_name = 'App_Login'

urlpatterns = [
    path('signup/', views.sign_up, name='signup'),
    path('login/', views.login_page, name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('profile/', views.profile, name='profile'),
    path('change-profile/', views.user_change, name='user_change'),
    path('password/', views.pass_change, name='pass_change'),
    path('add-picture/', views.add_pro_pic, name='add_pro_pic'),
    path('change-picture/', views.change_pro_pic, name='change_pro_pic'),
]

JealousyWorld/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

from django.conf import settings
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('App_Login.urls')),
    path('blog/', include('App_Feed.urls')),
    path('', views.Index, name='index')
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

App_Feed/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Blog(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='post_author')
    blog_title = models.CharField(max_length=264, verbose_name="Post Title")
    slug = models.SlugField(max_length=264, unique=True)
    blog_content = models.TextField(verbose_name="Description")
    blog_image = models.ImageField(upload_to='blog_images', verbose_name="Image", blank=True, null=True)
    publish_date = models.DateTimeField(auto_now_add=True)
    update_date = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-publish_date',]

    def __str__(self):
        return self.blog_title

class Comment(models.Model):
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE, related_name='blog_comment')
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user_comment')
    comment = models.TextField()
    comment_date = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('-comment_date',)
        
    def __str__(self):
        return self.comment

class Likes(models.Model):
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE, related_name="liked_blog")
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="liker_user")


    def __str__(self):
        return self.user + " likes " + self.blog

App_Feed/forms.py
from django import forms
from App_Feed.models import Blog, Comment


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('comment',)

App_Feed/views.py
from django.shortcuts import render, HttpResponseRedirect
from django.views.generic import CreateView, UpdateView, ListView, DetailView, View, TemplateView, DeleteView
from App_Feed.models import Blog, Comment, Likes
from django.urls import reverse, reverse_lazy
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from App_Feed.forms import CommentForm
import uuid

# Create your views here.

class MyBlogs(LoginRequiredMixin, TemplateView):
    template_name = 'App_Feed/my_blogs.html'

class CreateBlog(LoginRequiredMixin, CreateView):
    model = Blog
    template_name = 'App_Feed/create_blog.html'
    fields = ('blog_title', 'blog_content', 'blog_image',)

    def form_valid(self, form):
        blog_obj = form.save(commit=False)
        blog_obj.author = self.request.user
        title = blog_obj.blog_title
        blog_obj.slug = title.replace(" ", "-") + "-" + str(uuid.uuid4())
        blog_obj.save()
        return HttpResponseRedirect(reverse('index'))

class BlogList(ListView):
    context_object_name = 'blogs'
    model = Blog
    template_name = 'App_Feed/blog_list.html'

@login_required 
def blog_details(request, slug):
    blog = Blog.objects.get(slug=slug)
    comment_form = CommentForm()
    already_liked = Likes.objects.filter(blog=blog, user= request.user)
    if already_liked:
        liked = True
    else:
        liked = False
    if request.method == 'POST':
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            comment = comment_form.save(commit=False)
            comment.user = request.user
            comment.blog = blog
            comment.save()
            return HttpResponseRedirect(reverse('App_Feed:blog_details', kwargs={'slug':slug}))
    return render(request, 'App_Feed/blog_details.html', context={'blog':blog, 'comment_form':comment_form, 'liked':liked,})

@login_required
def liked(request, pk):
    blog = Blog.objects.get(pk=pk)
    user = request.user
    already_liked = Likes.objects.filter(blog=blog, user=user)
    if not already_liked:
        liked_post = Likes(blog=blog, user=user)
        liked_post.save()
    return HttpResponseRedirect(reverse('App_Feed:blog_details', kwargs={'slug':blog.slug}))

@login_required
def unliked(request, pk):
    blog = Blog.objects.get(pk=pk)
    user = request.user
    already_liked = Likes.objects.filter(blog=blog, user=user)
    already_liked.delete()
    return HttpResponseRedirect(reverse('App_Feed:blog_details', kwargs={'slug':blog.slug}))

# class UpdateBlog(LoginRequiredMixin, UpdateView):
#     model = Blog
#     fields = ('blog_title', 'blog_content', 'blog_image')
#     template_name = 'App_Feed/edit_blog.html'

#     def get_success_url(self, **kwargs):
#         return reverse_lazy('App_Feed:blog_details', kwargs={'slug':self.object.slug})


class UpdateBlog(LoginRequiredMixin, UpdateView):
    model = Blog
    fields = ('blog_title', 'blog_content', 'blog_image')
    template_name = 'App_Feed/edit_blog.html'

    def form_valid(self, form):
        blog = form.save(commit=False)

        # If no new image is uploaded, keep the existing one
        if not self.request.FILES.get('blog_image') and self.object.blog_image:
            blog.blog_image = self.object.blog_image

        blog.save()
        return HttpResponseRedirect(self.get_success_url())

    def get_success_url(self, **kwargs):
        return reverse_lazy('App_Feed:blog_details', kwargs={'slug': self.object.slug})



class DeleteBlog(LoginRequiredMixin, DeleteView):
    model = Blog
    template_name = 'App_Feed/delete_blog.html'
    success_url = reverse_lazy('App_Feed:my_blogs')  # Redirect after deletion

    def get_queryset(self):
        # Ensure users can only delete their own posts
        return Blog.objects.filter(author=self.request.user)

templates/App_Feed/blog_details.html
{% extends 'base.html' %}
  {% load crispy_forms_tags %}
  {% load custom_filters %}
  
  {% block title_block %} {{ blog.blog_title }} {% endblock %}
  
  {% block body_block %}
    <div class="row">
      <div class="col-sm-6">
        <h2>{{ blog.blog_title }}</h2>
        <p>Posted By: {{ blog.author|anonymous_name:request.user }}</p>
        <p><i>Published On: {{ blog.publish_date }}</i></p>
        <p><i>Updated On: {{ blog.update_date }}</i></p>
        <h6>{{ blog.liked_blog.count }} Likes | {{ blog.blog_comment.count }} Comments</h6>
      </div>
      <div class="col-sm-6">
        <img src="/media/{{ blog.blog_image }}" width="100%">
      </div>
      <p>{{ blog.blog_content|linebreaks }}</p>
      <hr>
    </div>
  
    <div class="likes">
      {% if not liked %}
        <a href="{% url 'App_Feed:liked_post' pk=blog.pk %}">
          <i class="fa fa-thumbs-o-up fa-2x" aria-hidden="true"></i>
        </a>
      {% else %}
        <a href="{% url 'App_Feed:unliked_post' pk=blog.pk %}">
          <i class="fa fa-thumbs-o-down fa-2x" aria-hidden="true"></i>
        </a>
      {% endif %}
    </div>
  
    <div class="comments-section">
      <h5>Comments:</h5>
      {% for comment in blog.blog_comment.all %}
        <p><a href="#">@{{ comment.user|anonymous_name:request.user }}</a> {{ comment.comment }}<br><i>{{ comment.comment_date }}</i></p>
      {% endfor %}
    </div>
  
    <div class="comment-form">
      <form method="POST">
        {% csrf_token %}
        {{ comment_form|crispy }}
        <button type="submit" class="btn btn-primary btn-sm">Comment</button>
      </form>
    </div>
  
  {% endblock %}
  

templates/App_Feed/blog_list.html
{% extends 'base.html' %}
{% load custom_filters %}

{% block title_block %} Anonymous Feed {% endblock %}

{% block body_block %}
{% load static %}

<link rel="stylesheet" href="{% static 'css/list_style.css' %}">


<div class="container mt-4">
  {% for blog in blogs %}
  <div class="card mb-4 shadow">
    <div class="row g-0">

      <!-- Left Content -->
      <div class="col-md-8 p-4 d-flex flex-column justify-content-between">
        <div>
          {% if request.user.is_authenticated %}
            <a href="{% url 'App_Feed:blog_details' slug=blog.slug %}">
              <h4 class="card-title">{{ blog.blog_title }}</h4>
            </a>
          {% else %}
            <a href="{% url 'App_Login:login' %}">
              <h4 class="card-title">{{ blog.blog_title }}</h4>
            </a>
          {% endif %}

          <p class="card-text mt-2">{{ blog.blog_content|range_filter|linebreaks }}</p>
        </div>

        <div class="mt-3 d-flex justify-content-between align-items-center">
          <small class="text-muted">
            Posted by: {{ blog.author|anonymous_name:request.user }}
          </small>
          {% if request.user.is_authenticated %}
            <a href="{% url 'App_Feed:blog_details' slug=blog.slug %}" class="btn btn-sm btn-outline-primary">Read More</a>
          {% else %}
            <a href="{% url 'App_Login:signup' %}" class="btn btn-sm btn-outline-secondary">Read More</a>
          {% endif %}
        </div>
      </div>

      <!-- Right Image -->
      <div class="col-md-4">
        {% if request.user.is_authenticated %}
          <a href="{% url 'App_Feed:blog_details' slug=blog.slug %}">
        {% else %}
          <a href="{% url 'App_Login:signup' %}">
        {% endif %}
            <img src="/media/{{ blog.blog_image }}" alt="Blog Image" class="img-fluid h-100 w-100" style="object-fit: cover;">
          </a>
      </div>

    </div>
  </div>
  {% endfor %}
</div>
{% endblock %}

templates/App_Feed/create_blog.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title_block %} {% endblock %}
{% block body_block %}
<h2>What's on your mind?</h2>
<form method="POST" enctype="multipart/form-data">
  {{ form|crispy }}
  {% csrf_token %}
  <button type="submit" class="btn btn-success btn-sm">Publish</button>
</form>
{% endblock %}

templates/App_Feed/delete_blog.html
{% extends 'base.html' %}
{% block body_block %}
<h2>Are you sure you want to delete this post?</h2>
<p><strong>{{ object.blog_title }}</strong></p>
<form method="POST">
    {% csrf_token %}
    <button type="submit" class="btn btn-danger">Yes, Delete</button>
    <a href="{% url 'App_Feed:my_blogs' %}" class="btn btn-secondary">Cancel</a>
</form>
{% endblock %}

templates/App_Feed/edit_blog.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title_block %} {{blog.blog_title}} {% endblock %}
{% block body_block %}
{% if blog.author == user %}
<form method="POST">
{{form|crispy}}
{% csrf_token %}
<button type="submit" name="button">Update</button>
{% else %}
<p>You are not allowed to view this page. 404</p>
</form>
{% endif %}
{% endblock %}

templates/App_Feed/my_blogs.html
{% extends 'base.html' %}
{% load custom_filters %}

{% block title_block %} {{ user.username }} {% endblock %}

{% block body_block %}
  <div class="container">
    {% for blog in user.post_author.all %}
      <div class="blog-post">
        <h3>{{ blog.blog_title }}</h3>
        <h6>{{ blog.publish_date }}</h6>
        <div class="row">
          <div class="col-sm-4">
            <img src="/media/{{ blog.blog_image }}" width="100%">
          </div>
          <div class="col-sm-8">
            <p>{{ blog.blog_content|range_filter|linebreaks }}</p>
            <a href="{% url 'App_Feed:blog_details' slug=blog.slug %}">Read More</a>
          </div>
        </div>
      </br>
        <a href="{% url 'App_Feed:edit_blog' pk=blog.pk %}">✎ Edit</a>
        <a href="{% url 'App_Feed:delete_blog' blog.pk %}" class="btn btn-danger btn-sm">Delete</a>
        <hr>
      </div>
    {% endfor %}
  </div>
{% endblock %}