App_Feed/urls.py
from django.urls import path
from App_Feed import views
from App_Feed.views import DeleteBlog

app_name = 'App_Feed'

urlpatterns = [
    path('', views.BlogList.as_view(), name='blog_list'),
    path('write/', views.CreateBlog.as_view(), name='create_blog'),
    path('details/<slug:slug>', views.blog_details, name='blog_details'),
    path('liked/<pk>/', views.liked, name='liked_post'),
    path('unliked/<pk>/', views.unliked, name='unliked_post'),
    path('my-blogs/', views.MyBlogs.as_view(), name='my_blogs'),
    path('edit/<pk>/', views.UpdateBlog.as_view(), name='edit_blog'),
    path('delete/<pk>/', DeleteBlog.as_view(), name='delete_blog'),
]

App_Login/urls.py
from django.urls import path
from App_Login import views

app_name = 'App_Login'

urlpatterns = [
    path('signup/', views.sign_up, name='signup'),
    path('login/', views.login_page, name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('profile/', views.profile, name='profile'),
    path('change-profile/', views.user_change, name='user_change'),
    path('password/', views.pass_change, name='pass_change'),
    path('add-picture/', views.add_pro_pic, name='add_pro_pic'),
    path('change-picture/', views.change_pro_pic, name='change_pro_pic'),
]

JealousyWorld/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

from django.conf import settings
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('App_Login.urls')),
    path('blog/', include('App_Feed.urls')),
    path('', views.Index, name='index')
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>{% block title_block %}InverseMe{% endblock %}</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- Bootstrap 4 -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>

  <!-- Font Awesome -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

  <!-- Custom CSS -->
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>

  <nav class="navbar navbar-expand-md navbar-dark custom-navbar">
    <a class="navbar-brand" href="{% url 'index' %}">
      {% comment %} <img src="/media/Logo.jpeg" alt="Logo"> {% endcomment %}
      <h3>InverseMe</h3>
    </a>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navMenu">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navMenu">
      <ul class="navbar-nav ml-auto">
        {% if user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'App_Feed:create_blog' %}">Post 📝</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">
            @{{ user.username }}
          </a>
          <div class="dropdown-menu dropdown-menu-right">
            <a class="dropdown-item" href="{% url 'App_Feed:my_blogs' %}">📰 My Posts</a>
            <a class="dropdown-item" href="{% url 'App_Login:profile' %}">👤 Profile</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="{% url 'App_Login:logout' %}">⏻ Logout</a>
          </div>
        </li>
        {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'App_Login:signup' %}">🔑 Sign Up</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'App_Login:login' %}">➜🚪 Login</a>
        </li>
        {% endif %}
      </ul>
    </div>
  </nav>

  <div class="container main-container">
    {% block body_block %}
    {% endblock %}
  </div>

</body>
</html>